### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Omikorin** [goldfivve/The-Bus-Problem-SO2#1]
Yo, got no requirements.txt, so project dosen't run

**Comment by szandala** [comment]
Oh c'mon...
yes, requirements shoud be present, but just install pygame,
And mute Your speakers as music sux...

**Comment by DocentSzachista** [comment]
> Yo, got no requirements.txt, so project dosen't run

Ya mean "Docent"?

**Comment by Omikorin** [comment]
> > Yo, got no requirements.txt, so project dosen't run
> 
> Ya mean "Docent"?

Docen't to czasem
